services:
  js-app-1:
   <<: &js-app-config
    container_name: js-app-1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LOG_LEVEL=INFO
      - PORT=80
      - DB_HOST=postgres-db
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_PORT=5432
      - DB_SCHEMA=people
      - DB_MAX_CONN=25
      - DB_CONN_TIMEOUT=20000
      - CLUSTER_WORKER=2
    depends_on:
      - postgres-db
    expose:
      - 80
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: '0.125'
          memory: '0.5GB'
  js-app-2:
    <<: *js-app-config
    container_name: js-app-2
  nginx:
    container_name: nginx
    image: nginx:1.27.1-alpine
    volumes:
      - ./scripts/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - js-app-1
      - js-app-2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.125'
          memory: '0.5GB'
    networks:
      - default
  postgres-db:
    image: postgres:16.4-alpine3.20
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: people
    ports:
    - "5432:5432"
    volumes:
    - ./scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    - ./scripts/postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command:
      ["postgres","-c","config_file=/docker-entrypoint-initdb.d/postgresql.conf"]
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: '1.125'
          memory: '1.5GB'
  pgadmin-ui: # This is to help monitor postgres on tests. Not part of rinha.
    image: dpage/pgadmin4
    container_name: pgadmin-ui
    environment:
      PGADMIN_DEFAULT_EMAIL: "david.socer@hotmail.com"
      PGADMIN_DEFAULT_PASSWORD: "5J4JgqSffm8f7rE"
    ports:
      - "16543:80"
    volumes:
      - ~/.pgadmin4-data:/var/lib/pgadmin
    depends_on:
      - postgres-db
    networks:
      - default
networks:
  default:
    driver: bridge